<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Koushik" failures="1" tests="6" name="Test2" time="28.818" errors="0" timestamp="2025-10-05T19:02:02 IST">
  <testcase classname="TestPackage.login" name="loginTest" time="3.755"/>
  <testcase classname="TestPackage.login" name="loginTest" time="3.25"/>
  <testcase classname="TestPackage.login" name="loginTest" time="3.32">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at Pages.loginPage.loginSwaglab(loginPage.java:32)
at TestPackage.login.loginTest(login.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="TestPackage.login" name="loginTest" time="8.22"/>
  <testcase classname="TestPackage.login" name="loginTest" time="2.903"/>
  <testcase classname="TestPackage.login" name="loginTest" time="2.831"/>
</testsuite> <!-- Test2 -->
