<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Koushik" failures="1" tests="6" name="loginStepDefination.loginTestrunner" time="26.467" errors="0" timestamp="2025-10-05T18:28:56 IST" skipped="0">
  <testcase classname="loginStepDefination.loginTestrunner" name="runScenario" time="3.396"/>
  <testcase classname="loginStepDefination.loginTestrunner" name="runScenario" time="3.274">
    <failure message="The following asserts failed:
	expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at loginStepDefination.loginStepdefination.verify(loginStepdefination.java:44)
at âœ½.login successfull page is displayed and verify "https://www.saucedemo.com/inventory.html"(file:///C:/Users/koush/eclipse-workspace/PageObjectModel2/src/test/java/features/login.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="loginStepDefination.loginTestrunner" name="runScenario" time="4.590"/>
  <testcase classname="loginStepDefination.loginTestrunner" name="runScenario" time="8.335"/>
  <testcase classname="loginStepDefination.loginTestrunner" name="runScenario" time="3.296"/>
  <testcase classname="loginStepDefination.loginTestrunner" name="runScenario" time="3.576"/>
</testsuite> <!-- loginStepDefination.loginTestrunner -->
